
package com.easylearnjava.webserviceprovider;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://webserviceprovider.easylearnjava.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     * @throws CalculatorException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webserviceprovider.easylearnjava.com/Calculator/add2NumbersRequest", output = "http://webserviceprovider.easylearnjava.com/Calculator/add2NumbersResponse", fault = {
        @FaultAction(className = CalculatorException_Exception.class, value = "http://webserviceprovider.easylearnjava.com/Calculator/add2Numbers/Fault/CalculatorException")
    })
    public int add2Numbers(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws CalculatorException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     * @throws CalculatorException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webserviceprovider.easylearnjava.com/Calculator/sub2NumbersRequest", output = "http://webserviceprovider.easylearnjava.com/Calculator/sub2NumbersResponse", fault = {
        @FaultAction(className = CalculatorException_Exception.class, value = "http://webserviceprovider.easylearnjava.com/Calculator/sub2Numbers/Fault/CalculatorException")
    })
    public int sub2Numbers(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws CalculatorException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     * @throws CalculatorException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webserviceprovider.easylearnjava.com/Calculator/mul2NumbersRequest", output = "http://webserviceprovider.easylearnjava.com/Calculator/mul2NumbersResponse", fault = {
        @FaultAction(className = CalculatorException_Exception.class, value = "http://webserviceprovider.easylearnjava.com/Calculator/mul2Numbers/Fault/CalculatorException")
    })
    public int mul2Numbers(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws CalculatorException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     * @throws CalculatorException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webserviceprovider.easylearnjava.com/Calculator/div2NumbersRequest", output = "http://webserviceprovider.easylearnjava.com/Calculator/div2NumbersResponse", fault = {
        @FaultAction(className = CalculatorException_Exception.class, value = "http://webserviceprovider.easylearnjava.com/Calculator/div2Numbers/Fault/CalculatorException")
    })
    public double div2Numbers(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws CalculatorException_Exception
    ;

}
