
package com.easylearnjava.webserviceprovider;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CalculatorException", targetNamespace = "http://webserviceprovider.easylearnjava.com/")
public class CalculatorException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CalculatorException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public CalculatorException_Exception(String message, CalculatorException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public CalculatorException_Exception(String message, CalculatorException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.easylearnjava.webserviceprovider.CalculatorException
     */
    public CalculatorException getFaultInfo() {
        return faultInfo;
    }

}
